/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cron;

import exceptions.InvalidInputException;
import exceptions.ParsingException;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {


    @Test(expected = ParsingException.class)
    public void expectException_whenInvalidInput() throws ParsingException {
        App cron = new App();
        String[] empty = new String[0];
        cron.parse(empty, "");
    }

    @Test
    public void noException_whenValidInput() throws ParsingException {
        App cron = new App();
        String[] empty = new String[0];
        cron.parse("1 1 1 1 1".split(" "), "1");
    }

    @Test(expected = InvalidInputException.class) 
    public void expectException_whenGivenWrongMinute() throws InvalidInputException {
        App cron = new App();
        cron.parseField(new Minute(), "60");
    } 

    @Test(expected = InvalidInputException.class)
    public void expectException_whenGivenWrongHour() throws InvalidInputException {
        App cron = new App();
        cron.parseField(new Hour(), "24");
    }

    @Test(expected = InvalidInputException.class)
    public void expectException_whenGivenWrongDayMonth() throws InvalidInputException {
        App cron = new App();
        cron.parseField(new DayMonth(), "32");
    }

    @Test(expected = InvalidInputException.class)
    public void expectException_whenGivenWrongMonth() throws InvalidInputException {
        App cron = new App();
        cron.parseField(new Month(), "13");
    }

    @Test(expected = InvalidInputException.class) 
    public void expectException_whenGivenWrongDayWeek() throws InvalidInputException {
        App cron = new App();
        cron.parseField(new DayWeek(), "7");
    }

    @Test
    public void testParseMinute() throws InvalidInputException {
        App cron = new App();
        String expected = "1";
        String actual =  cron.parseField(new Minute(), "1");
        assertEquals(actual, expected);
    }

    @Test
    public void testParseMinuteRange() throws InvalidInputException {
        App cron = new App();
        String expected = "1 2 3 4 5";
        String actual =  cron.parseField(new Minute(), "1-5");
        assertEquals(actual, expected);
    }

    @Test
    public void testParseMinuteSequence() throws InvalidInputException {
        App cron = new App();
        String expected = "1 3 5";
        String actual =  cron.parseField(new Minute(), "1,3,5");
        assertEquals(actual, expected);
    }

    @Test
    public void testParseMinuteStep() throws InvalidInputException {
        App cron = new App();
        String expected = "0 5 10 15 20 25 30 35 40 45 50 55";
        assertEquals(expected, cron.parseField(new Minute(), "*/5"));
    }

    @Test
    public void testParseMinuteAny() throws InvalidInputException {
        App cron = new App();
        String expected = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 59";
        assertEquals(expected, cron.parseField(new Minute(), "*"));
    }
        
}
